In [6]:
from sklearn.neural_network import MLPClassifier
import pandas as pd

In [7]:
df = pd.read_csv("matchups1-1.csv",  nrows=999999)

In [8]:
df.head(20)

,P_MATCH_ID,GOLDEARNED,TOTALMINIONSKILLED,WIN,KILLS,ASSISTS,DEATHS,CHAMPION,VISIONSCORE,PUUID,TOTALDAMAGEDEALTTOCHAMPIONS,SUMMONERNAME,GAMEVERSION,Unnamed: 13
0,BR1_2304032235_utility,5218,16,False,1,6,6,Bard,28,UNNl1KcPO98UoXiuRpQBefEKJbtCF_80b0_2s0Cwa5FiYi...,4500,batata 12121212,11.13.382.1241,NaN
1,BR1_2304032235_utility,7515,29,True,1,20,1,Blitzcrank,40,w2DLeo91qdfD72dpGgapMOKh_4IZ9IMF29neabiS0QTe8W...,7716,love yourseIf,11.13.382.1241,NaN
2,BR1_2304032235_jungle,9197,47,False,5,5,5,Nocturne,17,wDtmVguiopT93yrxtv2L88LxAVWC8E2fj_F3FDW81nCuSU...,9696,NTM HACKER,11.13.382.1241,NaN
3,BR1_2304032235_jungle,10564,37,True,6,8,4,Kayn,12,zVKtTZrdKVIpXwIMlsuSQjwOgqxx0DMhnWDFL7MrAKxXZq...,15291,unsuri,11.13.382.1241,NaN
4,BR1_2303451507_top,10598,158,False,6,8,7,Pantheon,17,sTevUOXxKjNW7dpbtyu9wjn8KZxzN63_f2MfGc1EALDjtq...,20568,Nome e Numeros,11.13.382.1241,NaN
5,BR1_2303451507_top,13000,174,True,10,4,6,Mordekaiser,18,r7sMT1QKsGE_Y5O7o2tQMU8v6A5BA6hsyCKnvKqo7fAsxJ...,20672,Duianr,11.13.382.1241,NaN
6,BR1_2303451507_middle,11020,142,False,9,11,6,Sylas,22,k3QNwCsiDne5mCM9ci1uRAmOy8R6-5CJpZNltTWXq_G8Lr...,18444,mid 171806,11.13.382.1241,NaN
7,BR1_2303451507_middle,13362,186,True,6,3,7,Yasuo,18,YtuHbTHdywjKS6NxBeS2L-9_8crTSS382DR1Y1T_OcWzaL...,16851,Shinrà,11.13.382.1241,NaN
8,BR1_2303451507_bottom,9786,145,False,3,13,10,MissFortune,19,HvoYvTf-GpNH2BvHQcuD9qM1ftStcAS8ytWGMcbENaEF19...,18302,Eco de LUXden,11.13.382.1241,NaN
9,BR1_2303451507_bottom,15347,189,True,17,10,7,Samira,14,ARsO3BJ9juU6ORmmv7pIO5NJlc3HNaMU4eBFYhMvI2fM-r...,35430,Petrocini,11.13.382.1241,NaN
10,BR1_2303451507_utility,8294,19,False,4,18,11,Bard,50,UNNl1KcPO98UoXiuRpQBefEKJbtCF_80b0_2s0Cwa5FiYi...,9129,batata 12121212,11.13.382.1241,NaN
11,BR1_2303451507_utility,8990,13,True,2,23,6,Janna,78,_ETsR9grRPF5P8H5gDD4VN4iyo-rUbU4TAiuUypeP9HOcF...,8356,Leona Professora,11.13.382.1241,NaN
12,BR1_2303451507_jungle,11541,32,False,11,13,8,Shaco,8,9XROSM2O8Apwuy6-OsdP33-N4KrJW3Nhn-NXs2XFeOkXKq...,26516,Kondö,11.13.382.1241,NaN
13,BR1_2303451507_jungle,12272,30,True,7,19,7,LeeSin,23,0zahzHqZl3AhIn1148CldD14-I5h04AHR8jvtRgxGgRt9Z...,22319,4807406179719,11.13.382.1241,NaN
14,BR1_2303306307_top,14537,192,True,10,3,9,Fiora,19,7YVYPJOVF3vgNDW38FWcqMWLPPr8UDBKrwUoYmpaO6L4of...,29914,Void nyan,11.13.382.1241,NaN
15,BR1_2303306307_top,11693,171,False,8,7,7,DrMundo,18,N06jWpDXBFDh9V0iwVn8k9pivhIrpdmxqgiPsAqdmiWlR2...,24153,Turbinatti,11.13.382.1241,NaN
16,BR1_2303306307_middle,12189,163,True,5,19,3,Morgana,21,TQ3wazSRQ8CuG8Zt-KdCCCeYy9KRMNrT_pY97L8tjArxxV...,24555,zezito00,11.13.382.1241,NaN
17,BR1_2303306307_middle,12120,193,False,8,8,9,Talon,18,QtaAHtAO6pk6t6nAB1lGyblAUgwMyS72xiFvmS6C-BDsbK...,21988,20032511 wqr,11.13.382.1241,NaN
18,BR1_2303306307_bottom,13952,146,True,16,11,7,Ezreal,16,X2NPNUvG3194k8XBj_KHQm7i47wSyxx0TrnapWspKISr7V...,34546,VK Vaynera do RJ,11.13.382.1241,NaN
19,BR1_2303306307_bottom,15052,226,False,12,11,6,Jinx,25,Sf58DlFix-3p9LEiM-mAN0ky3LGxYSHVWdOP4FJ5t4-8pJ...,30996,maYONEze Kaisara,11.13.382.1241,NaN

In [9]:
df['matchID'] = df['P_MATCH_ID'].str.split('_').str[1]
df['position'] = df['P_MATCH_ID'].str.split('_').str[2]

In [22]:
df[df["matchID"] =="2303451507"  ]

,P_MATCH_ID,GOLDEARNED,TOTALMINIONSKILLED,WIN,KILLS,ASSISTS,DEATHS,CHAMPION,VISIONSCORE,PUUID,TOTALDAMAGEDEALTTOCHAMPIONS,SUMMONERNAME,GAMEVERSION,Unnamed: 13,matchID,position
4,BR1_2303451507_top,10598,158,False,6,8,7,Pantheon,17,sTevUOXxKjNW7dpbtyu9wjn8KZxzN63_f2MfGc1EALDjtq...,20568,Nome e Numeros,11.13.382.1241,NaN,2303451507,top
5,BR1_2303451507_top,13000,174,True,10,4,6,Mordekaiser,18,r7sMT1QKsGE_Y5O7o2tQMU8v6A5BA6hsyCKnvKqo7fAsxJ...,20672,Duianr,11.13.382.1241,NaN,2303451507,top
6,BR1_2303451507_middle,11020,142,False,9,11,6,Sylas,22,k3QNwCsiDne5mCM9ci1uRAmOy8R6-5CJpZNltTWXq_G8Lr...,18444,mid 171806,11.13.382.1241,NaN,2303451507,middle
7,BR1_2303451507_middle,13362,186,True,6,3,7,Yasuo,18,YtuHbTHdywjKS6NxBeS2L-9_8crTSS382DR1Y1T_OcWzaL...,16851,Shinrà,11.13.382.1241,NaN,2303451507,middle
8,BR1_2303451507_bottom,9786,145,False,3,13,10,MissFortune,19,HvoYvTf-GpNH2BvHQcuD9qM1ftStcAS8ytWGMcbENaEF19...,18302,Eco de LUXden,11.13.382.1241,NaN,2303451507,bottom
9,BR1_2303451507_bottom,15347,189,True,17,10,7,Samira,14,ARsO3BJ9juU6ORmmv7pIO5NJlc3HNaMU4eBFYhMvI2fM-r...,35430,Petrocini,11.13.382.1241,NaN,2303451507,bottom
10,BR1_2303451507_utility,8294,19,False,4,18,11,Bard,50,UNNl1KcPO98UoXiuRpQBefEKJbtCF_80b0_2s0Cwa5FiYi...,9129,batata 12121212,11.13.382.1241,NaN,2303451507,utility
11,BR1_2303451507_utility,8990,13,True,2,23,6,Janna,78,_ETsR9grRPF5P8H5gDD4VN4iyo-rUbU4TAiuUypeP9HOcF...,8356,Leona Professora,11.13.382.1241,NaN,2303451507,utility
12,BR1_2303451507_jungle,11541,32,False,11,13,8,Shaco,8,9XROSM2O8Apwuy6-OsdP33-N4KrJW3Nhn-NXs2XFeOkXKq...,26516,Kondö,11.13.382.1241,NaN,2303451507,jungle
13,BR1_2303451507_jungle,12272,30,True,7,19,7,LeeSin,23,0zahzHqZl3AhIn1148CldD14-I5h04AHR8jvtRgxGgRt9Z...,22319,4807406179719,11.13.382.1241,NaN,2303451507,jungle

In [19]:
df.groupby(['matchID', 'WIN']).sum()

C:\Users\oqiu1\AppData\Local\Temp/ipykernel_5696/227684901.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby(['matchID', 'WIN']).sum()

                  GOLDEARNED  TOTALMINIONSKILLED  KILLS  ASSISTS  DEATHS  \
matchID    WIN
1001288357 False       31550                 467      5        4      21
           True        41019                 526     21       24       5
1001303651 False       46640                 486     22       26      39
           True        59825                 520     39       76      22
1001341779 False       51776                 723     18       28      28
...                      ...                 ...    ...      ...     ...
971925188  True        59431                 632     28       50      23
971929106  False       51277                 677     21       37      36
           True        63935                 691     36       54      21
971951103  False       18495                 277      3        3      13
           True        26348                 301     13       14       3

                  VISIONSCORE  TOTALDAMAGEDEALTTOCHAMPIONS  Unnamed: 13
matchID    WIN
1001288357 False           75                        42125          0.0
           True           107                        51758          0.0
1001303651 False          124                        85366          0.0
           True           135                        95004          0.0
1001341779 False          197                        56590          0.0
...                       ...                          ...          ...
971925188  True           124                        88083          0.0
971929106  False          195                        60394          0.0
           True           199                        76772          0.0
971951103  False           37                        15352          0.0
           True            42                        18395          0.0

[10558 rows x 8 columns]

In [16]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import json
import os
pd.set_option('float_format', '{:f}'.format)
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler 
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import MinMaxScaler
from sklearn.pipeline import Pipeline, FeatureUnion
from sklearn.preprocessing import OneHotEncoder

from sklearn.pipeline import make_pipeline
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
from sklearn.neural_network import MLPClassifier